server:
  port: 8080
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed. By default only text/html is compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed. Default value is 2048 bytes.
  undertow:
    threads:
      worker: 64 # Generally this should be reasonably high number, at least 10 per CPU core. https://undertow.io/undertow-docs/undertow-docs-2.0.0/index.html#blocking-handler
      io: 4 # One IO thread per CPU core. https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2