server:
  port: 8080
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed. By default, only text/html is compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed. Default value is 2048 bytes.
  undertow:
    threads:
      worker: 64 # Generally this should be reasonably high number, at least 10 per CPU core. https://undertow.io/undertow-docs/undertow-docs-2.0.0/index.html#blocking-handler
      io: 4 # One IO thread per CPU core. https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250 # É uma configuração em milissegundos. O ideal é manter baixo para estourar timeout logo e nao prender as threads
      max-lifetime: 600000 # Tempo máximo que uma conexão pode ficar aberta (10 minutos) - security
      maximum-pool-size: 20 # Mantemos até no máximo 20 conexões com o banco de dados. O ideal é manter baixo mesmo, pois é algo custoso para o banco gerenciar: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        connection.provider_disables_autocommit: true
    # Para aumentar a performance ao máximo, desabilitamos o auto-commit e o open-in-view
    # https://vladmihalcea.com/why-you-should-always-use-hibernate-connection-provider_disables_autocommit-for-resource-local-jpa-transactions
  mvc:
    servlet:
      path: /


springdoc:
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
swagger-servers-urls: http://localhost:${server.port}${spring.mvc.servlet.path}, http://127.0.0.1:${server.port}${spring.mvc.servlet.path}
